language: python
before_install:
  - pip install codecov
install:
  - pip install -q coverage
  - pip install pylint
  - pip install -r requirements.txt
  - pip install $EXTRA_INSTALLS

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1732ae62130d81fe54d8
    on_success: always
    on_failure: always
    on_start: always
env:
  - EXTRA_INSTALLS=pandas
  - EXTRA_INSTALLS=
python:
  - "2.7"
  - "3.3"
  - "3.4.4"
  - "3.5"
  - "3.6"
  - "pypy"
matrix:
  exclude:
    - python: "pypy"
      env: EXTRA_INSTALLS=pandas
    - python: "2.7"
      env: EXTRA_INSTALLS=
    - python: "3.3"
      env: EXTRA_INSTALLS=
    - python: "3.4.4"
      env: EXTRA_INSTALLS=
    - python: "3.5"
      env: EXTRA_INSTALLS=
    - python: "3.6"
      env: EXTRA_INSTALLS=

script: nosetests --with-coverage --cover-package=functional && pylint functional
after_success:
  - codecov
cache: pip
